const API_END_POINTS = {
  REGISTER: "/register",
  AUTH: "/auth",
  LOGIN: "/login",
  OTP: "/otp",
  VALIDATE: "/validate",
  SMS: "/sms",
  RETRY_VERIFICATION: "/retry-verification",
  RETRY_INITIATE: "/retry-initiate",
  VALIDATE_VERIFICATION_CODE: "/sms/check-verification-code",
  GENERATE: "/generate",
  VALIDATE_OTP: "/auth/otp/validate",
  USERS: "/users",
  REFRESH: "/refresh",
  STOCKS: "/stocks",
  BRAND: "/brand",
  PATTERN: "/pattern",
  TYRE_DETAIL: "/tyre-detail",
  TYRE_SIZE: "/tyre-size",
  VENDOR: "/vendor",
  TRANSPORT: "/transport",
  LOCATION: "/location",
  SEARCH: "search",
  CREATE: "/create",
  ORDERS: "/orders",
  USER: "/user",
  INFO: "/info",
  EXPORT: "/export",
  QUOTATIONS: "/quotations",
  USER_QUOTE: "/user-quote",
  MANAGE_QUOTATIONS: "/manage-quotations",
  SEND: "/send",
  STATUS: "status",
  TAKE: "take",
  PAGE: "page",
  SORT_BY: "sortBy",
  SPEED_RATING: "/speed-rating",
  LOAD_INDEX: "/load-index",
  PRODUCT_LINE: "/product-line",
  CUSTOMER_CATEGORY: "/customer-category",
  CUSTOMERS: "/customerS",
  SERVICES: "/services",
  OVERVIEW: "/overview",
  ADMIN: "/admin",
};

enum API_METHODS {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  PATCH = "PATCH",
  DELETE = "DELETE",
}

export { API_END_POINTS, API_METHODS };
